name: Update my coding stats graph

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  update-Readme:
    name: Update my Coding Graph in README
    runs-on: ubuntu-latest
    steps:
      - uses: tariksahni/coding-stats-wakatime@v1.0.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTION: ${{ github.action }}




