name: Update my coding stats graph

#on:
#  schedule:
#    - cron: '0 12 * * *'

on: [push]

jobs:
  update-Readme:
    name: Update my Coding Graph in README
    runs-on: ubuntu-latest
    steps:
      - uses: tariksahni/coding-stats-wakatime@v0.0.13
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}




